shallow_clone: true

environment:
  matrix:
    - nodejs_version: "10"

platform:
  - x64

branches:
  only:
  - master

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm install yarn@1.7.0 -g
  - netsh advfirewall firewall add rule name="SeleniumIn" dir=in action=allow protocol=TCP localport=4444
  - netsh advfirewall firewall add rule name="SeleniumOut" dir=out action=allow protocol=TCP localport=4444
  - cmd: set THEIA_SKIP_NPM_PREPARE=1 && yarn install
  - npx rimraf node_modules/@theia/electron/download

before_build:
  - node --version && npm --version && yarn --version && python --version

build_script:
  - yarn prepare

test_script:
  - appveyor-retry yarn test
